# Generated by Django 4.0.5 on 2022-06-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimg',
            new_name='profile_img',
        ),
    ]
