# Generated by Django 4.0.5 on 2022-06-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_profile_img_profile_profileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_user',
            new_name='Id_user',
        ),
    ]
